import "./globals.css";
import Navigation from "./components/Navigation";
import { Roboto, Work_Sans } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"],
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/me.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${workSans.variable}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
